[project]
name = "visie-agentes-ia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "agno>=2.6.4",
    "openai>=2.33.0",
    "opentelemetry-exporter-otlp-proto-grpc>=1.41.1",
    "opentelemetry-sdk>=1.41.1",
    "sqlalchemy>=2.0.49",
]
